module.exports = {
  SERVER:"http://localhost",
  AVATAR:"http://localhost/uploads/",
  SENDSMS:"http://localhost/api/auth/sendsms",
  REGISTER:'http://localhost/api/auth/register-web',
  CAPTCHA:'http://localhost/api/captcha',
  TYPEDRIVE:'http://localhost/api/type_drive',
  REFERRAL:'http://localhost/api/referral',
  VERIFYWEB:'http://localhost/api/auth/verifyweb',
  SIGNIN:'http://localhost/api/auth/sign-in-pass-word',
  USERACCOUNT:'http://localhost/api/auth/profile/',
  PROFILE_PICTRUE:'http://localhost/api/auth/avatar',
  PROFILE_CARD:'http://localhost/api/auth/card',
  PROFILE_DOC:'http://localhost/api/auth/doccument',
}
